### ISSUE TITLE
[FEATURE] `CATALOG INTEGRATION` required infra for unmanaged Iceberg tables

### ISSUE THREAD

**Issue by dataders** [Titan-Systems/titan#117]
related: #111 

managed Iceberg tables require an External Volume. If it's an unmanaged table, it also requires a Catalog integration.

While tire ticking, I've often had to drop/recreate/alter these objects as well as duplicate them for other environments. They're also hard to test because of the authentication and access controls they contain.

reference docs:
- [`CREATE CATALOG INTEGRATION`](https://docs.snowflake.com/en/sql-reference/sql/create-catalog-integration)

**Comment by teej** [comment]
Fixed in [v0.10](https://github.com/Titan-Systems/titan/releases/tag/v0.10.0)
