### ISSUE TITLE
DESC USER fails if MFA bypass has been set

### ISSUE THREAD

**Issue by GJMcClintock** [Titan-Systems/titan#157]
It appears to be expecting a positive INT. Had to bypass it for a backfill job yesterday and now get this error:

```TypeError: Expected User.mins_to_bypass_mfa to be <class 'int'>, got '-1391' instead```

**Comment by teej** [comment]
This just got fixed in [0.10.17](https://github.com/Titan-Systems/titan/commit/32af1223e5e369bf62d4400e90c5b6be32d32112), I'll publish now
