### ISSUE TITLE
Error thrown when trying to create a SNOWPARK-OPTIMIZED warehouse 

### ISSUE THREAD

**Issue by cyrdjet** [Titan-Systems/titan#158]
I ran into an error in trying to create a SNOWPARK-OPTIMIZED warehouse using the CLI, The error seems to be caused by the WAREHOUSE_TYPE value not getting wrapped in single quotes in the SQL statement that actually gets executed against the Snowflake account. The query generated is below. An attempt to create a STANDARD warehouse succeeds without the quotes (I believe) because Snowflake interprets the value STANDARD as a reserved keyword, but SNOWPARK-OPTIMIZED as string literal and expects it to be wrapped in quotes. Changing the value of the WarehouseType SNOWPARK_OPTIMIZED enum value to "'SNOWPARK-OPTIMIZED'" worked when I also changed my template value to the same but I anticipate that'll cause issues elsewhere. Just raising for awareness.

SQL compilation error: syntax error line 1 at position 105 unexpected '-'. syntax error line 1 at position 105 unexpected '-'. syntax error line 1 at position 116 unexpected 'warehouse_size'.

CREATE WAREHOUSE DEV_WH **warehouse_type = SNOWPARK-OPTIMIZED** warehouse_size = MEDIUM MAX_CLUSTER_COUNT = 1 MIN_CLUSTER_COUNT = 1 scaling_policy = STANDARD AUTO_SUSPEND = 600 AUTO_RESUME = TRUE INITIALLY_SUSPENDED = FALSE ENABLE_QUERY_ACCELERATION = FALSE QUERY_ACCELERATION_MAX_SCALE_FACTOR = 8 MAX_CONCURRENCY_LEVEL = 8 STATEMENT_QUEUED_TIMEOUT_IN_SECONDS = 0 STATEMENT_TIMEOUT_IN_SECONDS = 172800

**Comment by teej** [comment]
Snowflake is going to kill me with these weirdo syntax variants. I'll fix this now.

**Comment by teej** [comment]
Fixed in [v0.10.19](https://github.com/Titan-Systems/titan/releases/tag/v0.10.19). `pip install "titan-core>=0.10.19"`
