### ISSUE TITLE
No database specification for a schema

### ISSUE THREAD

**Issue by nic-sharesies** [Titan-Systems/titan#167]
Is there a reason why database isn't an option for a schema?

If I export my current schemas from Snowflake, I get a big file of all schemas but with no specification of database. If I then tried to run this same config file back into Snowflake I'd have every schema in the default database.

**Comment by teej** [comment]
Definitely a bug.

**Comment by teej** [comment]
Fixed in [v0.11.0](https://github.com/Titan-Systems/titan/releases/tag/v0.11.0).
