### ISSUE TITLE
Incorrect behaviour in Jupyter notebooks due to caching

### ISSUE THREAD

**Issue by jamesweakley** [Titan-Systems/titan#20]
I've been experimenting with Titan in a Jupyter notebook, was seeing some strange behaviour where roles were attempting to be created again.
Realised that `SHOW ROLES LIKE ....` etc were not actually running and found the `@cache` attributes.

If the cache is cleared at the start of each `plan()`, I figure it will all work fine in Jupyter.

**Comment by jamesweakley** [comment]
My workaround, which seems to work well:
https://github.com/omnata-labs/titan/commit/e7ca71a28ff2974d4caf353ebb93caab08d81171

**Comment by teej** [comment]
Fixed on head, shipping with 0.2.0
