### ISSUE TITLE
Relax strict requirements

### ISSUE THREAD

**Issue by bjorhn** [Titan-Systems/titan#25]
Would it be possible to relax some of the dependency version requirements of the project? I'm trying to give titan a try (looks great!) but the package specifically requires snowflake-snowpark-python 1.11.1 (I'm on 1.14.0).

It looks like the requirements are similarly strict for snowflake-connector-python and a few other packages.

**Comment by titan-teej** [comment]
I keep Titan aligned with the Snowflake conda channel to ensure that it can be deployed inside a Snowpark stored procedure or UDF. I'll go ahead and bump the dependencies now to match, which includes snowflake-snowpark-python @ 1.14.0

**Comment by bjorhn** [comment]
Ah, that makes sense!

Thanks, I appreciate it.
