### ISSUE TITLE
Improvement to Database resource

### ISSUE THREAD

**Issue by aleenprd** [Titan-Systems/titan#41]
https://github.com/Titan-Systems/titan/blob/a2d57e697f42862331024ab6f92e237ad2acd5d1/titan/resources/database.py#L16

This could be improved by conditionally changing the default owner to ACCOUNTADMIN when transient is true because time travel specs such as [DATA_RETENTION_TIME_IN_DAYS](https://docs.snowflake.com/en/sql-reference/parameters.html#label-data-retention-time-in-days) can only be applied by this role. If you do default owner with transient, you will get a confusing sql syntax error.

**Comment by teej** [comment]
Am I missing something here? This seems to work for me:

```
USE ROLE SYSADMIN;
CREATE TRANSIENT DATABASE tt_test;
ALTER DATABASE tt_test SET DATA_RETENTION_TIME_IN_DAYS = 0;
SHOW PARAMETERS IN DATABASE tt_test; // DATA_RETENTION_TIME_IN_DAYS value => 0
ALTER DATABASE tt_test SET DATA_RETENTION_TIME_IN_DAYS = 1;
SHOW PARAMETERS IN DATABASE tt_test; // DATA_RETENTION_TIME_IN_DAYS value => 1
```
