### ISSUE TITLE
Any Schema usage example

### ISSUE THREAD

**Issue by aleenprd** [Titan-Systems/titan#42]
https://github.com/Titan-Systems/titan/blob/a2d57e697f42862331024ab6f92e237ad2acd5d1/titan/resources/schema.py#L68

In Terraform it's extremely easy to manipulate objects in Snowflake, to create databases, schemas, etc. Here, with Titan, I don't understand how we are supposed to reference a schema. 

I would strongly suggest considering some type hinting and proper docstrings with documented meaning of args, until you have some sort of Wiki (to make users more confident in trying this product out).

**Comment by teej** [comment]
This is a bug, I'll fix in the next release.

**Comment by teej** [comment]
For any resource, you can specify the container via kwargs.

As a string:
```python
sch = Schema(
  name = "some_schema",
  database = "my_test_db",
)
```

As an object:
```python
db = Database(name = "my_test_db")

sch = Schema(
  name = "some_schema",
  database = db,
)
```

You can also specify if programmatically using the (currently undocumented) `add` method:
```python
db = Database(name = "my_test_db")
sch = Schema(name = "some_schema")
db.add(sch)
```

I'll add docs for this.
