### ISSUE TITLE
Unable to apply grants using qualified schema names to roles

### ISSUE THREAD

**Issue by ravi77o** [Titan-Systems/titan#45]
I was unable to apply a `GRANT` statement using the YAML configuration. 
```yaml
grants:
 - GRANT ALL ON SCHEMA my_db.my_schema TO ROLE my_role
```

When I apply the changes, `fetch_remote_state()` [catches](https://github.com/Titan-Systems/titan/blob/a2d57e697f42862331024ab6f92e237ad2acd5d1/titan/blueprint.py#L578-L579) the exception  raised [here](https://github.com/Titan-Systems/titan/blob/a2d57e697f42862331024ab6f92e237ad2acd5d1/titan/data_provider.py#L785) because `fqn.database` is. not set.

I tried parsing the grant statement directly and got the response below:
```python
grant = Grant.from_sql("GRANT USAGE ON SCHEMA my_db.my_schema TO ROLE my_role")
```
![image](https://github.com/Titan-Systems/titan/assets/357102/4399af58-f1b0-4004-8f63-30f25f8b17cf)

I'm happy to assist with the fix but may need some direction.

**Comment by teej** [comment]
Looks like this isn't supported yet. Let me see if I can add this now.

**Comment by teej** [comment]
I have a temporary fix just for schemas on the branch [bugfix/fully-qualified-names-in-sql](https://github.com/Titan-Systems/titan/tree/bugfix/fully-qualified-names-in-sql) but need another day to ship a permanent fix

**Comment by teej** [comment]
Fixed in https://github.com/Titan-Systems/titan/releases/tag/v0.5.3
