### ISSUE TITLE
GrantOnAll requires owner = ""

### ISSUE THREAD

**Issue by toadies** [Titan-Systems/titan#78]
`owner` is not required field for GrantOnAll and default is None.  However, the resource fails when trying to execute `_create_ownership_refs`, requiring owner to not be None.

```
grant = GrantOnAll(priv="SELECT", on_type="TABLE", in_type="SCHEMA", in_name="db.sch", to="some_role")
self.add(grant)
plan = self.plan(session)

/venv/lib/python3.10/site-packages/titan/blueprint.py", line 700, in _create_ownership_refs
    identifier = parse_identifier(tag_name)
AttributeError: 'NoneType' object has no attribute 'name'
```

To avoid the error, I need to add `owner=""` when creating my `GrantOnAll` permission.

**Comment by teej** [comment]
Fixed in [v0.8.6](https://github.com/Titan-Systems/titan/releases/tag/v0.8.6)
