### ISSUE TITLE
GrantOnAll YAML equivalent

### ISSUE THREAD

**Issue by GClunies** [Titan-Systems/titan#94]
Is there a way to issue the equivalent of `GrantOnAll()` using the YAML config? I didn't find anything in the docs/repo. Thanks for this great package!

**Comment by titan-teej** [comment]
It should be `grant_on_alls:`. I'll add this to the docs.

**Comment by teej** [comment]
Fixed in [v0.9](https://github.com/Titan-Systems/titan/releases/tag/v0.9.1)
